# Generated by Django 3.0.7 on 2020-11-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilephoto',
            fields=[
                ('id_photo', models.IntegerField(primary_key=True, serialize=False)),
                ('picture_location', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'profilephoto',
                'managed': False,
            },
        ),
    ]
