# Generated by Django 3.0.7 on 2021-01-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
